// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Chunk struct {
	UploadID   uuid.UUID `json:"upload_id"`
	ChunkNo    int32     `json:"chunk_no"`
	Size       int32     `json:"size"`
	Checksum   string    `json:"checksum"`
	ReceivedAt time.Time `json:"received_at"`
}

type Job struct {
	ID        uuid.UUID `json:"id"`
	UploadID  uuid.UUID `json:"upload_id"`
	Status    string    `json:"status"`
	ErrorCode *string   `json:"error_code"`
	ErrorMsg  *string   `json:"error_msg"`
	Retries   int32     `json:"retries"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Task struct {
	ID         uuid.UUID  `json:"id"`
	JobID      uuid.UUID  `json:"job_id"`
	Kind       string     `json:"kind"`
	Status     string     `json:"status"`
	Attempt    int32      `json:"attempt"`
	Payload    []byte     `json:"payload"`
	Result     []byte     `json:"result"`
	ErrorMsg   *string    `json:"error_msg"`
	StartedAt  *time.Time `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type Upload struct {
	ID             uuid.UUID  `json:"id"`
	OwnerID        string     `json:"owner_id"`
	Filename       string     `json:"filename"`
	ContentType    string     `json:"content_type"`
	TotalSize      int64      `json:"total_size"`
	ChunkSize      int32      `json:"chunk_size"`
	TotalChunks    int32      `json:"total_chunks"`
	ReceivedBytes  int64      `json:"received_bytes"`
	Status         string     `json:"status"`
	Bucket         string     `json:"bucket"`
	Key            string     `json:"key"`
	ChecksumSha256 *string    `json:"checksum_sha256"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	ExpiresAt      *time.Time `json:"expires_at"`
}
