// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appendChunk = `-- name: AppendChunk :one
INSERT INTO chunks (upload_id, chunk_no, size, checksum)
VALUES ($1, $2, $3, $4)
ON CONFLICT (upload_id, chunk_no) DO UPDATE
    SET size = EXCLUDED.size, checksum = EXCLUDED.checksum, received_at = now()
RETURNING upload_id, chunk_no, size, checksum, received_at
`

type AppendChunkParams struct {
	UploadID uuid.UUID `json:"upload_id"`
	ChunkNo  int32     `json:"chunk_no"`
	Size     int32     `json:"size"`
	Checksum string    `json:"checksum"`
}

func (q *Queries) AppendChunk(ctx context.Context, arg AppendChunkParams) (Chunk, error) {
	row := q.db.QueryRow(ctx, appendChunk,
		arg.UploadID,
		arg.ChunkNo,
		arg.Size,
		arg.Checksum,
	)
	var i Chunk
	err := row.Scan(
		&i.UploadID,
		&i.ChunkNo,
		&i.Size,
		&i.Checksum,
		&i.ReceivedAt,
	)
	return i, err
}

const countChunks = `-- name: CountChunks :one
SELECT COUNT(*) FROM chunks WHERE upload_id = $1
`

func (q *Queries) CountChunks(ctx context.Context, uploadID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChunks, uploadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, upload_id, status) VALUES ($1, $2, $3) RETURNING id, upload_id, status, error_code, error_msg, retries, created_at, updated_at
`

type CreateJobParams struct {
	ID       uuid.UUID `json:"id"`
	UploadID uuid.UUID `json:"upload_id"`
	Status   string    `json:"status"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.ID, arg.UploadID, arg.Status)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMsg,
		&i.Retries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, job_id, kind, status, payload) VALUES ($1, $2, $3, $4, $5) RETURNING id, job_id, kind, status, attempt, payload, result, error_msg, started_at, finished_at, created_at, updated_at
`

type CreateTaskParams struct {
	ID      uuid.UUID `json:"id"`
	JobID   uuid.UUID `json:"job_id"`
	Kind    string    `json:"kind"`
	Status  string    `json:"status"`
	Payload []byte    `json:"payload"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.JobID,
		arg.Kind,
		arg.Status,
		arg.Payload,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.Status,
		&i.Attempt,
		&i.Payload,
		&i.Result,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (id, owner_id, filename, content_type, total_size, chunk_size, total_chunks, status, bucket, key, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, owner_id, filename, content_type, total_size, chunk_size, total_chunks, received_bytes, status, bucket, key, checksum_sha256, created_at, updated_at, expires_at
`

type CreateUploadParams struct {
	ID          uuid.UUID  `json:"id"`
	OwnerID     string     `json:"owner_id"`
	Filename    string     `json:"filename"`
	ContentType string     `json:"content_type"`
	TotalSize   int64      `json:"total_size"`
	ChunkSize   int32      `json:"chunk_size"`
	TotalChunks int32      `json:"total_chunks"`
	Status      string     `json:"status"`
	Bucket      string     `json:"bucket"`
	Key         string     `json:"key"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.ID,
		arg.OwnerID,
		arg.Filename,
		arg.ContentType,
		arg.TotalSize,
		arg.ChunkSize,
		arg.TotalChunks,
		arg.Status,
		arg.Bucket,
		arg.Key,
		arg.ExpiresAt,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.ContentType,
		&i.TotalSize,
		&i.ChunkSize,
		&i.TotalChunks,
		&i.ReceivedBytes,
		&i.Status,
		&i.Bucket,
		&i.Key,
		&i.ChecksumSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, upload_id, status, error_code, error_msg, retries, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMsg,
		&i.Retries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByUpload = `-- name: GetJobByUpload :one
SELECT id, upload_id, status, error_code, error_msg, retries, created_at, updated_at FROM jobs WHERE upload_id = $1
`

func (q *Queries) GetJobByUpload(ctx context.Context, uploadID uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByUpload, uploadID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMsg,
		&i.Retries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, job_id, kind, status, attempt, payload, result, error_msg, started_at, finished_at, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.Status,
		&i.Attempt,
		&i.Payload,
		&i.Result,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUpload = `-- name: GetUpload :one
SELECT id, owner_id, filename, content_type, total_size, chunk_size, total_chunks, received_bytes, status, bucket, key, checksum_sha256, created_at, updated_at, expires_at FROM uploads WHERE id = $1
`

func (q *Queries) GetUpload(ctx context.Context, id uuid.UUID) (Upload, error) {
	row := q.db.QueryRow(ctx, getUpload, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.ContentType,
		&i.TotalSize,
		&i.ChunkSize,
		&i.TotalChunks,
		&i.ReceivedBytes,
		&i.Status,
		&i.Bucket,
		&i.Key,
		&i.ChecksumSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const incrementReceivedBytes = `-- name: IncrementReceivedBytes :one
UPDATE uploads SET received_bytes = received_bytes + $2, updated_at = now()
WHERE id = $1 RETURNING id, owner_id, filename, content_type, total_size, chunk_size, total_chunks, received_bytes, status, bucket, key, checksum_sha256, created_at, updated_at, expires_at
`

type IncrementReceivedBytesParams struct {
	ID            uuid.UUID `json:"id"`
	ReceivedBytes int64     `json:"received_bytes"`
}

func (q *Queries) IncrementReceivedBytes(ctx context.Context, arg IncrementReceivedBytesParams) (Upload, error) {
	row := q.db.QueryRow(ctx, incrementReceivedBytes, arg.ID, arg.ReceivedBytes)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.ContentType,
		&i.TotalSize,
		&i.ChunkSize,
		&i.TotalChunks,
		&i.ReceivedBytes,
		&i.Status,
		&i.Bucket,
		&i.Key,
		&i.ChecksumSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listChunks = `-- name: ListChunks :many
SELECT upload_id, chunk_no, size, checksum, received_at FROM chunks WHERE upload_id = $1 ORDER BY chunk_no
`

func (q *Queries) ListChunks(ctx context.Context, uploadID uuid.UUID) ([]Chunk, error) {
	rows, err := q.db.Query(ctx, listChunks, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chunk{}
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.UploadID,
			&i.ChunkNo,
			&i.Size,
			&i.Checksum,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredUploads = `-- name: ListExpiredUploads :many
SELECT id, owner_id, filename, content_type, total_size, chunk_size, total_chunks, received_bytes, status, bucket, key, checksum_sha256, created_at, updated_at, expires_at FROM uploads WHERE status = 'uploading' AND expires_at < now() FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListExpiredUploads(ctx context.Context) ([]Upload, error) {
	rows, err := q.db.Query(ctx, listExpiredUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Upload{}
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Filename,
			&i.ContentType,
			&i.TotalSize,
			&i.ChunkSize,
			&i.TotalChunks,
			&i.ReceivedBytes,
			&i.Status,
			&i.Bucket,
			&i.Key,
			&i.ChecksumSha256,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByJob = `-- name: ListTasksByJob :many
SELECT id, job_id, kind, status, attempt, payload, result, error_msg, started_at, finished_at, created_at, updated_at FROM tasks WHERE job_id = $1 ORDER BY created_at
`

func (q *Queries) ListTasksByJob(ctx context.Context, jobID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Kind,
			&i.Status,
			&i.Attempt,
			&i.Payload,
			&i.Result,
			&i.ErrorMsg,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUploadChecksum = `-- name: SetUploadChecksum :one
UPDATE uploads SET checksum_sha256 = $2, status = $3, updated_at = now()
WHERE id = $1 RETURNING id, owner_id, filename, content_type, total_size, chunk_size, total_chunks, received_bytes, status, bucket, key, checksum_sha256, created_at, updated_at, expires_at
`

type SetUploadChecksumParams struct {
	ID             uuid.UUID `json:"id"`
	ChecksumSha256 *string   `json:"checksum_sha256"`
	Status         string    `json:"status"`
}

func (q *Queries) SetUploadChecksum(ctx context.Context, arg SetUploadChecksumParams) (Upload, error) {
	row := q.db.QueryRow(ctx, setUploadChecksum, arg.ID, arg.ChecksumSha256, arg.Status)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.ContentType,
		&i.TotalSize,
		&i.ChunkSize,
		&i.TotalChunks,
		&i.ReceivedBytes,
		&i.Status,
		&i.Bucket,
		&i.Key,
		&i.ChecksumSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs SET status = $2, error_code = $3, error_msg = $4, retries = $5, updated_at = now()
WHERE id = $1 RETURNING id, upload_id, status, error_code, error_msg, retries, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	ErrorCode *string   `json:"error_code"`
	ErrorMsg  *string   `json:"error_msg"`
	Retries   int32     `json:"retries"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMsg,
		arg.Retries,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMsg,
		&i.Retries,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskCompleted = `-- name: UpdateTaskCompleted :one
UPDATE tasks SET status = 'completed', result = $2, finished_at = now(), updated_at = now()
WHERE id = $1 RETURNING id, job_id, kind, status, attempt, payload, result, error_msg, started_at, finished_at, created_at, updated_at
`

type UpdateTaskCompletedParams struct {
	ID     uuid.UUID `json:"id"`
	Result []byte    `json:"result"`
}

func (q *Queries) UpdateTaskCompleted(ctx context.Context, arg UpdateTaskCompletedParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskCompleted, arg.ID, arg.Result)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.Status,
		&i.Attempt,
		&i.Payload,
		&i.Result,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskFailed = `-- name: UpdateTaskFailed :one
UPDATE tasks SET status = 'retrying', error_msg = $2, updated_at = now()
WHERE id = $1 RETURNING id, job_id, kind, status, attempt, payload, result, error_msg, started_at, finished_at, created_at, updated_at
`

type UpdateTaskFailedParams struct {
	ID       uuid.UUID `json:"id"`
	ErrorMsg *string   `json:"error_msg"`
}

func (q *Queries) UpdateTaskFailed(ctx context.Context, arg UpdateTaskFailedParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskFailed, arg.ID, arg.ErrorMsg)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.Status,
		&i.Attempt,
		&i.Payload,
		&i.Result,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStarted = `-- name: UpdateTaskStarted :one
UPDATE tasks SET status = 'processing', attempt = attempt + 1, started_at = now(), updated_at = now()
WHERE id = $1 RETURNING id, job_id, kind, status, attempt, payload, result, error_msg, started_at, finished_at, created_at, updated_at
`

func (q *Queries) UpdateTaskStarted(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStarted, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.Status,
		&i.Attempt,
		&i.Payload,
		&i.Result,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUploadStatus = `-- name: UpdateUploadStatus :one
UPDATE uploads SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, owner_id, filename, content_type, total_size, chunk_size, total_chunks, received_bytes, status, bucket, key, checksum_sha256, created_at, updated_at, expires_at
`

type UpdateUploadStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUploadStatus(ctx context.Context, arg UpdateUploadStatusParams) (Upload, error) {
	row := q.db.QueryRow(ctx, updateUploadStatus, arg.ID, arg.Status)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.ContentType,
		&i.TotalSize,
		&i.ChunkSize,
		&i.TotalChunks,
		&i.ReceivedBytes,
		&i.Status,
		&i.Bucket,
		&i.Key,
		&i.ChecksumSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
